#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=root@docean
readonly TARGET_PATH=/home/root/councillor-runner
readonly TARGET_ARCH=x86_64-unknown-linux-gnu
readonly SOURCE_PATH=target/${TARGET_ARCH}/release/councillor-runner

CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=${TARGET_ARCH}-gcc cargo build --release --target=${TARGET_ARCH}

rsync -aiz --progress ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} sudo systemctl restart councillor-bot.service
